// <auto-generated />
using System;
using System.Text.Json;
using Gateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CeConversationid")
                        .HasColumnType("text")
                        .HasColumnName("ce_conversationid");

                    b.Property<string>("CeDatacontenttype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ce_datacontenttype");

                    b.Property<string>("CeDataschema")
                        .HasColumnType("text")
                        .HasColumnName("ce_dataschema");

                    b.Property<string>("CeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ce_id");

                    b.Property<string>("CeSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ce_source");

                    b.Property<string>("CeSubject")
                        .HasColumnType("text")
                        .HasColumnName("ce_subject");

                    b.Property<string>("CeTenant")
                        .HasColumnType("text")
                        .HasColumnName("ce_tenant");

                    b.Property<DateTimeOffset>("CeTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ce_time");

                    b.Property<string>("CeTraceparent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ce_traceparent");

                    b.Property<string>("CeTracestate")
                        .HasColumnType("text")
                        .HasColumnName("ce_tracestate");

                    b.Property<string>("CeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ce_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_name");

                    b.Property<string>("ErrorType")
                        .HasColumnType("text")
                        .HasColumnName("error_type");

                    b.Property<string>("OpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("send")
                        .HasColumnName("op_name");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("send")
                        .HasColumnName("op_type");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Retries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retries");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("text")
                        .HasColumnName("server_address");

                    b.Property<int?>("ServerPort")
                        .HasColumnType("integer")
                        .HasColumnName("server_port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("text")
                        .HasColumnName("subscription_name");

                    b.HasKey("Id");

                    b.HasIndex("CeConversationid")
                        .HasDatabaseName("idx_outbox_conversation");

                    b.HasIndex("CeType")
                        .HasDatabaseName("idx_outbox_cetype");

                    b.HasIndex("DestinationName")
                        .HasDatabaseName("idx_outbox_destination");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_status_created_at");

                    b.ToTable("outbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
